graph = dict()
graph = {
        "name": "grafo 1",
        "nodes": [
  { "id": '1', "type": 'default', "data": { "label": '' }, "position": { "x": 100, "y": 50 }, "style": { "backgroundColor": 'white', "borderColor": 'white' } },
  { "id": '2', "type": 'default', "data": { "label": '' }, "position": { "x": 200, "y": 50 }, "style": { "backgroundColor": 'white', "borderColor": 'white' } },
  { "id": '3', "type": 'default', "data": { "label": '' }, "position": { "x": 300, "y": 50 }, "style": { "backgroundColor": 'white', "borderColor": 'white' } },
  { "id": '4', "type": 'default', "data": { "label": '' }, "position": { "x": 100, "y": 150 }, "style": { "backgroundColor": 'white', "borderColor": 'white' } },
  { "id": '5', "type": 'default', "data": { "label": '' }, "position": { "x": 300, "y": 150 }, "style": { "backgroundColor": 'white', "borderColor": 'white' } },
  { "id": '6', "type": 'default', "data": { "label": '' }, "position": { "x": 200, "y": 250 }, "style": { "backgroundColor": 'white', "borderColor": 'white' } },
],
        "edges": [
  { "id": "e1-2", "source": "1", "target": "2" },
  { "id": "e2-3", "source": "2", "target": "3" },
  { "id": "e1-4", "source": "1", "target": "4" },
  {"id": "e1-5", "source": "1", "target": "5"},
  { "id": "e4-6", "source": "4", "target": "6" },
  { "id": "e6-5", "source": "6", "target": "5" },
  { "id": "e5-3", "source": "5", "target": "3" },
  { "id": "e2-6", "source": "2", "target": "6" }
],
        "nodesNumber": 6,
        "isConnected": True,
        "isComplete": False,
        "isWeighted": False,
        "isDirected": False
    }

graph1 = dict()
graph1 = {'name': 'grafo EJEM TALLER2',
 'nodes': [{'id': '1',
   'type': 'default',
   'data': {'label': 'A'},
   'position': {'x': 100, 'y': 50},
   'style': {'backgroundColor': 'white', 'borderColor': 'white'}},
  {'id': '2',
   'type': 'default',
   'data': {'label': 'B'},
   'position': {'x': 200, 'y': 50},
   'style': {'backgroundColor': 'white', 'borderColor': 'white'}},
  {'id': '3',
   'type': 'default',
   'data': {'label': 'C'},
   'position': {'x': 300, 'y': 50},
   'style': {'backgroundColor': 'white', 'borderColor': 'white'}},
  {'id': '4',
   'type': 'default',
   'data': {'label': 'D'},
   'position': {'x': 100, 'y': 150},
   'style': {'backgroundColor': 'yellow', 'borderColor': 'white'}},
  {'id': '5',
   'type': 'default',
   'data': {'label': 'E'},
   'position': {'x': 200, 'y': 150},
   'style': {'backgroundColor': 'yellow', 'borderColor': 'white'}},
  {'id': '6',
   'type': 'default',
   'data': {'label': 'F'},
   'position': {'x': 300, 'y': 150},
   'style': {'backgroundColor': 'yellow', 'borderColor': 'white'}}],
 'edges': [{'id': 'e1-5',
   'source': '1',
   'target': '5',
   'type': 'straight',
   'label': '0.5'},
  {'id': 'e1-6',
   'source': '1',
   'target': '6',
   'type': 'straight',
   'label': '0.5'},
  {'id': 'e2-4',
   'source': '2',
   'target': '4',
   'type': 'straight',
   'label': '0.8'},
  {'id': 'e2-6',
   'source': '2',
   'target': '6',
   'type': 'straight',
   'label': '0.5'},
  {'id': 'e3-4',
   'source': '3',
   'target': '4',
   'type': 'straight',
   'label': '0.5'},
  {'id': 'e3-5',
   'source': '3',
   'target': '5',
   'type': 'straight',
   'label': '0.6'}
  ],
 'nodesNumber': 6,
 'isConnected': True,
 'isComplete': False,
 'isWeighted': True,
 'isDirected': False}